### ISSUE TITLE
Push new version to npm

### ISSUE THREAD

**Issue by danieldunderfelt** [developit/babel-preset-preact#3]
Hi!

I noticed the published version does not include the added dependencies. Could this be pushed to npm?

Thanks!

**Comment by developit** [comment]
Unfortunately, I do not have publish rights to the npm package 😓

I'm hoping @jmas will add me ❤️

(background: I created this repo but never published it to npm since I just use the babel plugins directly. @jmas published it but I believe it was not yet in a working state, so the npm package can't really be used as it is)

**Comment by jmas** [comment]
Hello, sorry, I thought that I pushed `jmas/babel-preset-preact` but looks like it is global package. So I added you @developit (https://www.npmjs.com/~developit) as collaborator.

**Comment by developit** [comment]
heh - awesome, much appreciated @jmas!

**Comment by jmas** [comment]
@developit ;) thanks for package, it helped.
